
package com.frenzi.webservice;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.7-b01 
 * Generated source version: 2.2
 * 
 */
@WebService(name = "File", targetNamespace = "http://webservice.frenzi.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface File {


    /**
     * 
     * @param arg0
     * @return
     *     returns byte[]
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getFile", targetNamespace = "http://webservice.frenzi.com/", className = "com.frenzi.webservice.GetFile")
    @ResponseWrapper(localName = "getFileResponse", targetNamespace = "http://webservice.frenzi.com/", className = "com.frenzi.webservice.GetFileResponse")
    @Action(input = "http://webservice.frenzi.com/File/getFileRequest", output = "http://webservice.frenzi.com/File/getFileResponse")
    public byte[] getFile(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<java.lang.String>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getFilesName", targetNamespace = "http://webservice.frenzi.com/", className = "com.frenzi.webservice.GetFilesName")
    @ResponseWrapper(localName = "getFilesNameResponse", targetNamespace = "http://webservice.frenzi.com/", className = "com.frenzi.webservice.GetFilesNameResponse")
    @Action(input = "http://webservice.frenzi.com/File/getFilesNameRequest", output = "http://webservice.frenzi.com/File/getFilesNameResponse")
    public List<String> getFilesName(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
